services:
  frontend:
    image: jigglyy/frontend:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.role == frontend
      replicas: 1
    ports:
      - "8080:80"
    networks:
      - todo-app-network
    depends_on:
      - backend

  backend:
    image: jigglyy/backend:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.role == backend
      replicas: 1
    environment:
      PORT: 3000
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: todoapp
      DB_PASSWORD: secret123
      DB_NAME: todos
    networks:
      - todo-app-network
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.role == database
      replicas: 1
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: todos
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  todo-app-network:
    driver: overlay

volumes:
  db_data:
    driver: local
