apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-backend
  labels:
    {{- include "my-fullstack-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port | default 3000 }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "my-fullstack-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend