apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-config
data:
  greetingMessage: {{ .Values.backend.config.greetingMessage | quote | default "Hello from Helm!" }}
