apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "my-fullstack-app-chart.name" . }}
    tier: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
