apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-fullstack-app-chart.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-fullstack-app-chart.name" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ include "my-fullstack-app-chart.name" . }}
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
